export 'actors/actors_by_movie_provider.dart';
export 'actors/actors_repository_provider.dart';
export 'movies/initial_loading_provider.dart';
export 'movies/movie_info_provider.dart';
export 'movies/movies_providers.dart';
export 'movies/movies_repository_provider.dart';
export 'movies/movies_slideshow_provider.dart';
export 'search/search_movies_provider.dart';
export 'storage/local_storage_provider.dart';
export 'storage/favorites_movies_and_series_provider.dart';
export 'storage/tv_series_storage_provider.dart';
// export 'storage/tv_storage_provider.dart';
export 'theme/theme_provider.dart';
export 'theme/theme_dark_provider.dart';
export 'tv_series/tv_series_provider.dart';
export 'tv_series/tv_series_repossitory_provider.dart';
export 'tv_series/tv_serie_info.dart';
